### PR TITLE
Add server,json dotenfFile convention

### PR DESCRIPTION
**Pull request by bdw429s**

### CODE REVIEW

**Comment by bdw429s** [comment]
@jclausen This pull should also close https://github.com/commandbox-modules/commandbox-dotenv/issues/13 and https://github.com/commandbox-modules/commandbox-dotenv/issues/14

It adds a `dotenvFile` key convention to the `server.json` OR the config `server.defaults` (additive, not overridden) which can contain a comma delimited list of file globbing patterns of properties file to load when the server starts.  This is done in addition to the `<webroot>/.env` convention.

```
# Load all properties files in the web root as well as foo.properties in the config folder.
server set dotenvFile=*.properties,config/foo.properties
```

**Comment by elpete** [comment]
@bdw429s Can you add to the readme about the new configuration locations?  Thanks!

**Comment by bdw429s** [comment]
Ohh, yes.  Good call :+1:

**Comment by bdw429s** [comment]
@elpete Note added to the readme about the new functionality

**Comment by elpete** [comment]
Published as [v2.2.0](https://forgebox.io/view/commandbox-dotenv/version/2.2.0)

**Pull request merged**
