### PR TITLE
Update LoadEnvForServers.cfc

### PR DESCRIPTION
**Pull request by evagoras**
Missing dependency and wrong struct calling for setting the JVM.

### CODE REVIEW

**Comment by bdw429s** [comment]
@elpete :point_up: ?

**Comment by elpete** [comment]
Sorry, I wasn’t subscribed to this repo.

**Comment by elpete** [comment]
Is this still needed? We split the interceptors to a `preServerStart` and an `onServerStart` around the time this PR was submitted.

**Comment by bdw429s** [comment]
How are you not subscribed to your own repo? :)  @evagoras can you pls confirm if your fix is still needed on the latest version of the code?

**Comment by elpete** [comment]
I don’t think it was the default for a while. There are a few repos like that for me.

**Comment by elpete** [comment]
Hi, @evagoras.  Is this still needed?

**Comment by evagoras** [comment]
@elpete it looks like this is no longer needed. Thanks for the automatic fix!

**Pull request closed without merging**
