### PR TITLE
Escape cazy stuff if it happens to exist in the value

### PR DESCRIPTION
**Pull request by bdw429s**

### CODE REVIEW

**Comment by bdw429s** [comment]
I was testing with an `.env` that included the following entries:

```
bar=brad "the fish" wo & od
quotedString="This is a & quoted string"
again="C:\\my\\path\\"
```
Note I've also made some fixes to how CommandBox parses JVM Args that goes along with this, but the examples above are sort of broken either way right now so basically it will all work once people have this new version of dotenv and the latest CommandBox.

**Comment by elpete** [comment]
Just a thought, is https://github.com/bdw429s/PropertyFile a better place for this PR? Then it applies in all the places using it under the hood. 

Or is this just a case for passing JVM args? In that case I can merge here.

**Comment by bdw429s** [comment]
@elpete The escapes I'm adding here are very specific to how CommandBox parses the JVM arg string when starting a server.

**Comment by bdw429s** [comment]
@elpete Also, a random site note-- the code I'm touching here needs to go away at some point in the future.  Now that CommandBox loads the .env into the box environment and passes the box environment to the server process, this is redundant.  The only purpose the .env -> JVM arg code serves at this point is:
* backwards compat for people on older CommandBox versions
* In case someone had specific code in their app to get the values ONLY out of Java system props and didn't look in the system environment.

**Comment by elpete** [comment]
Understood. Thanks.

**Pull request merged**
