### PR TITLE
Log to the console when a .env file is loaded

### PR DESCRIPTION
**Pull request by jsteinshouer**
PR for issue #1. I also refactored some duplicate code into a model component. Let me know if you would like anything changed.

### CODE REVIEW

**Comment by elpete** [comment]
Here's a thought: what if we add a `verbose` setting to print out the env struct when loaded.  This could be toggled on or off based on user preference.

Something like `config set modules.commandbox-dotenv.printOnLoad`.

Thoughts?

**Comment by jsteinshouer** [comment]
I think that sounds good. Are you thinking to replace the log message I added or in addition too it?

**Comment by elpete** [comment]
Let's make it in addition.

**Comment by jsteinshouer** [comment]
I added a commit for logging the properties and values. I didn't implement it for the `onServerStart` interceptor as I thought it would be redundant. The args are already logged via the server start command anyway.

**Comment by elpete** [comment]
Looks great!  Thanks!

**Pull request merged**
